import toast from "react-hot-toast";
import { supabase } from "../services/supabase";

export async function insertDemoTransactions() {
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (!user) throw new toast.error("❌ User not logged in");
  if (authError) throw new toast.error("❌ Auth error: " + authError.message);
  // Removing the announcement of demo transactions for April-November 2025
  const { error: deleteError } = await supabase
    .from("transactions")
    .delete()
    .match({ user_id: user.id }) // To remove all demo data, comment out the lines below gte, lte
    .gte("date", "2025-04-01")
    .lte("date", "2025-11-30");

  if (deleteError) {
    console.error("❌ Delete error:", deleteError.message);
    throw new Error("Delete error: " + deleteError.message);
  }

  const demoData = [
    // 🌸 April
    {
      description: "Salary April",
      amount: 24000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-04-01",
    },
    {
      description: "Rent April",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-04-03",
    },
    {
      description: "Groceries",
      amount: 2100,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-04-05",
    },
    {
      description: "Coffee and snacks",
      amount: 450,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Cafe",
      date: "2025-04-05",
    },
    {
      description: "Groceries",
      amount: 2200,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-04-06",
    },
    {
      description: "Pharmacy purchase",
      amount: 520,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Pharmacy",
      date: "2025-04-07",
    },
    {
      description: "Convenience store snacks",
      amount: 320,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Convenience store",
      date: "2025-04-08",
    },
    {
      description: "Electricity bill",
      amount: 580,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-04-10",
    },
    {
      description: "Movie night tickets",
      amount: 300,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Movie Theater",
      date: "2025-04-12",
    },
    {
      description: "Pharmacy",
      amount: 430,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Pharmacy",
      date: "2025-04-12",
    },
    {
      description: "Taxi ride home",
      amount: 370,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Taxi",
      date: "2025-04-12",
    },
    {
      description: "Children's toys",
      amount: 1200,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Toys",
      date: "2025-04-15",
    },
    {
      description: "Home insurance payment",
      amount: 1500,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Home insurance",
      date: "2025-04-15",
    },
    {
      description: "Jewelry purchase",
      amount: 3400,
      type: "withdraw",
      main_category: "Clothing and gear",
      sub_category: "Jewelry and accessories",
      date: "2025-04-20",
    },
    {
      description: "Pet supplies",
      amount: 850,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Pets",
      date: "2025-04-22",
    },

    // 🌼 May
    {
      description: "Salary May",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-05-01",
    },
    {
      description: "Rent May",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-05-03",
    },
    {
      description: "Sporting goods store",
      amount: 1800,
      type: "withdraw",
      main_category: "Clothing and gear",
      sub_category: "Sporting goods",
      date: "2025-05-05",
    },
    {
      description: "Groceries",
      amount: 2400,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-05-06",
    },
    {
      description: "Electricity",
      amount: 600,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-05-10",
    },
    {
      description: "Credit card payment",
      amount: 5400,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Credit card payment",
      date: "2025-05-10",
    },
    {
      description: "Taxi fare",
      amount: 380,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Taxi",
      date: "2025-05-12",
    },
    {
      description: "Coffee shop",
      amount: 350,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Cafe",
      date: "2025-05-14",
    },
    {
      description: "Dental check-up",
      amount: 1600,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Dentist",
      date: "2025-05-18",
    },

    // ☀️ June
    {
      description: "Salary June",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-06-01",
    },
    {
      description: "Rent June",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-06-03",
    },
    {
      description: "Groceries",
      amount: 2300,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-06-05",
    },
    {
      description: "Gardening flowers",
      amount: 1300,
      type: "withdraw",
      main_category: "Home and garden",
      sub_category: "Garden and flowers",
      date: "2025-06-07",
    },
    {
      description: "Fast food lunch",
      amount: 450,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Fast food",
      date: "2025-06-10",
    },
    {
      description: "Phone service monthly",
      amount: 750,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Phone service",
      date: "2025-06-11",
    },
    {
      description: "Pharmacy",
      amount: 350,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Pharmacy",
      date: "2025-06-15",
    },
    {
      description: "Freelance project",
      amount: 5000,
      type: "income",
      main_category: "Income",
      sub_category: "Other income",
      date: "2025-06-20",
    },
    {
      description: "Mechanic service",
      amount: 2800,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Mechanic",
      date: "2025-06-23",
    },

    // 🌻 July
    {
      description: "Salary July",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-07-01",
    },
    {
      description: "Rent July",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-07-01",
    },
    {
      description: "Groceries",
      amount: 2150,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-07-03",
    },
    {
      description: "Online gaming app purchase",
      amount: 300,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Apps and gaming",
      date: "2025-07-04",
    },
    {
      description: "Movie tickets",
      amount: 260,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Movie Theater",
      date: "2025-07-07",
    },
    {
      description: "Tool for home repair",
      amount: 950,
      type: "withdraw",
      main_category: "Home and garden",
      sub_category: "Tools",
      date: "2025-07-09",
    },
    {
      description: "Streaming service",
      amount: 120,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Streaming services",
      date: "2025-07-11",
    }, {
      description: "Childcare supplies",
      amount: 1150,
      type: "withdraw",
      main_category: "Children",
      sub_category: "Other child expenses",
      date: "2025-07-17",
    },
    {
      description: "Car parts purchase",
      amount: 2400,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Car parts and maintenance",
      date: "2025-07-22",
    },
    // 🌾 August
    {
      description: "Salary August",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-08-01",
    },
    {
      description: "Rent August",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-08-03",
    },
    {
      description: "Cash withdrawal",
      amount: 4000,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Cash machine",
      date: "2025-08-04",
    },
    {
      description: "Online course on UI design",
      amount: 1200,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Training and education",
      date: "2025-08-05",
    },
    {
      description: "Groceries",
      amount: 2250,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-08-06",
    },
    {
      description: "Beauty salon visit",
      amount: 950,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Beauty",
      date: "2025-08-07",
    },
    {
      description: "Dinner out",
      amount: 900,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Restaurant",
      date: "2025-08-08",
    },
    {
      description: "Cabin rental weekend",
      amount: 3800,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Cabin",
      date: "2025-08-08",
    },
    {
      description: "Public transport monthly card",
      amount: 650,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Public transport",
      date: "2025-08-09",
    },
    {
      description: "Gym membership",
      amount: 1200,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Wellbeing",
      date: "2025-08-10",
    },
    {
      description: "Newspaper subscription",
      amount: 180,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Newspaper",
      date: "2025-08-11",
    },
    {
      description: "Fuel",
      amount: 1500,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Fuel and charging",
      date: "2025-08-12",
    },
    {
      description: "Magazine subscription",
      amount: 350,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Magazines",
      date: "2025-08-13",
    },
    {
      description: "Other child expenses",
      amount: 1100,
      type: "withdraw",
      main_category: "Children",
      sub_category: "Other child expenses",
      date: "2025-08-14",
    },
    {
      description: "Pet food",
      amount: 700,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Pets",
      date: "2025-08-15",
    },
    {
      description: "Eye exam at optometrist",
      amount: 1300,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Eye care",
      date: "2025-08-16",
    },
    {
      description: "Interest from savings",
      amount: 350,
      type: "income",
      main_category: "Income",
      sub_category: "Dividends",
      date: "2025-08-18",
    },
    {
      description: "Train ticket to nearby city",
      amount: 780,
      type: "withdraw",
      main_category: "Travel",
      sub_category: "Phone tickets",
      date: "2025-08-19",
    },
    {
      description: "Electricity bill",
      amount: 580,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-08-20",
    },
    {
      description: "Charity donation",
      amount: 500,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Membership and charity",
      date: "2025-08-21",
    },
    {
      description: "Gambling site deposit",
      amount: 400,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Gambling",
      date: "2025-08-23",
    },
    {
      description: "Online course",
      amount: 950,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Training and education",
      date: "2025-08-25",
    },
    // September
    {
      description: "Salary September",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-09-01",
    },
    {
      description: "Rent September",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-09-03",
    },
    {
      description: "Groceries",
      amount: 2300,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-09-05",
    },
    {
      description: "Streaming subscription",
      amount: 150,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Streaming services",
      date: "2025-09-06",
    },
    {
      description: "Dinner at restaurant",
      amount: 1100,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Restaurant",
      date: "2025-09-08",
    },
    {
      description: "Monthly public transport card",
      amount: 650,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Public transport",
      date: "2025-09-09",
    },
    {
      description: "Pharmacy purchase",
      amount: 520,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Pharmacy",
      date: "2025-09-10",
    },
    {
      description: "Electricity bill",
      amount: 590,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-09-12",
    },
    {
      description: "Online book order",
      amount: 850,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Training and education",
      date: "2025-09-14",
    },
    {
      description: "Pet food",
      amount: 780,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Pets",
      date: "2025-09-15",
    },
    {
      description: "Coffee and snacks",
      amount: 420,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Cafe",
      date: "2025-09-17",
    },
    {
      description: "Freelance work payment",
      amount: 6000,
      type: "income",
      main_category: "Income",
      sub_category: "Other income",
      date: "2025-09-18",
    },
    {
      description: "Fuel for car",
      amount: 1550,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Fuel and charging",
      date: "2025-09-20",
    },
    {
      description: "Children's clothing",
      amount: 2000,
      type: "withdraw",
      main_category: "Children",
      sub_category: "Clothes",
      date: "2025-09-22",
    },
    {
      description: "Monthly gym fee",
      amount: 1200,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Wellbeing",
      date: "2025-09-25",
    },
    {
      description: "Magazine subscription",
      amount: 350,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Magazines",
      date: "2025-09-27",
    },
    {
      description: "Interest from savings",
      amount: 340,
      type: "income",
      main_category: "Income",
      sub_category: "Dividends",
      date: "2025-09-28",
    },
    // 🌰 October
    {
      description: "Salary October",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-10-01",
    },
    {
      description: "Rent October",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-10-03",
    },
    {
      description: "Groceries",
      amount: 2400,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-10-05",
    },
    {
      description: "Electricity bill",
      amount: 590,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-10-07",
    },
    {
      description: "Taxi ride",
      amount: 400,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Taxi",
      date: "2025-10-10",
    },
    {
      description: "Cinema tickets",
      amount: 450,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Movie Theater",
      date: "2025-10-12",
    },
    {
      description: "Coffee and snacks",
      amount: 380,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Cafe",
      date: "2025-10-14",
    },
    {
      description: "Children's clothing",
      amount: 1000,
      type: "withdraw",
      main_category: "Children",
      sub_category: "Clothes",
      date: "2025-10-16",
    },
    {
      description: "Car maintenance",
      amount: 2200,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Car maintenance",
      date: "2025-10-18",
    },
    {
      description: "Pet supplies",
      amount: 850,
      type: "withdraw",
      main_category: "Hobby and leisure",
      sub_category: "Pets",
      date: "2025-10-20",
    },
    {
      description: "Home repair tools",
      amount: 950,
      type: "withdraw",
      main_category: "Home and garden",
      sub_category: "Tools",
      date: "2025-10-22",
    },
    {
      description: "Fuel",
      amount: 1500,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Fuel and charging",
      date: "2025-10-25",
    },
    {
      description: "Beauty salon visit",
      amount: 1200,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Beauty",
      date: "2025-10-28",
    },
    {
      description: "Interest from savings",
      amount: 350,
      type: "income",
      main_category: "Income",
      sub_category: "Dividends",
      date: "2025-10-30",
    },
    // 🍂 November
    {
      description: "Salary November",
      amount: 25000,
      type: "income",
      main_category: "Income",
      sub_category: "Wages",
      date: "2025-11-01",
    },
    {
      description: "Rent November",
      amount: 11000,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Mortgage",
      date: "2025-11-03",
    },
    {
      description: "Groceries",
      amount: 2500,
      type: "withdraw",
      main_category: "Groceries",
      sub_category: "Supermarket",
      date: "2025-11-05",
    },
    {
      description: "Electricity bill",
      amount: 600,
      type: "withdraw",
      main_category: "Fixed living expenses",
      sub_category: "Electricity",
      date: "2025-11-07",
    },
    {
      description: "Cinema tickets",
      amount: 500,
      type: "withdraw",
      main_category: "Media and entertainment",
      sub_category: "Movie Theater",
      date: "2025-11-09",
    },
    {
      description: "Taxi ride",
      amount: 450,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Taxi",
      date: "2025-11-11",
    },
    {
      description: "Gift for friend's birthday",
      amount: 1500,
      type: "withdraw",
      main_category: "Gifts and donations",
      sub_category: "Birthday gift",
      date: "2025-11-13",
    },
    {
      description: "Fuel",
      amount: 1700,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Fuel and charging",
      date: "2025-11-15",
    },
    {
      description: "Gym membership",
      amount: 1200,
      type: "withdraw",
      main_category: "Health and wellbeing",
      sub_category: "Wellbeing",
      date: "2025-11-17",
    },
    {
      description: "Monthly public transport card",
      amount: 650,
      type: "withdraw",
      main_category: "Transportation and vehicles",
      sub_category: "Public transport",
      date: "2025-11-19",
    },
    {
      description: "Online shopping (Clothes)",
      amount: 2500,
      type: "withdraw",
      main_category: "Clothing and gear",
      sub_category: "Clothing",
      date: "2025-11-21",
    },
    {
      description: "Lunch at restaurant",
      amount: 700,
      type: "withdraw",
      main_category: "Cafe and restaurant",
      sub_category: "Restaurant",
      date: "2025-11-23",
    },
    {
      description: "Family trip (Accommodation)",
      amount: 7500,
      type: "withdraw",
      main_category: "Travel",
      sub_category: "Accommodation",
      date: "2025-11-25",
    },
    {
      description: "Interest from savings",
      amount: 380,
      type: "income",
      main_category: "Income",
      sub_category: "Dividends",
      date: "2025-11-28",
    },
    {
      description: "Charity donation",
      amount: 800,
      type: "withdraw",
      main_category: "Miscellaneous",
      sub_category: "Charity",
      date: "2025-11-29",
    },
  ].map((t) => ({ ...t, user_id: user.id }));

  const { error } = await supabase.from("transactions").insert(demoData);
  if (error) throw new Error("Insert demo error: " + error.message);

  toast("✅ Demo transactions inserted");
}
