export const categories = {
  "Cafe and restaurant": [
    "Bars and nightlife",
    "Cafe",
    "Cafeteria",
    "Candy",
    "Convenience store",
    "Fast food",
    "Restaurant",
  ],
  "Car insurance and car loan": [],
  "Children": [
    "Children's store",
    "Other child expenses",
  ],
  "Clothing and gear": [
    "Clothing",
    "Jewelry and accessories",
    "Shoes",
    "Sporting goods",
  ],
  "Fixed living expenses": [
    "Alarm",
    "Electricity",
    "Home insurance",
    "Housing expenses",
    "Internet",
    "Mortgage",
    "Municipal fees",
    "Phone service",
    "Property management",
    "Rental and sales",
  ],
  "Groceries": [
    "Grocery store",
    "Other household items",
  ],
  "Health and wellbeing": [
    "Beauty",
    "Dentist",
    "Eye care",
    "Health goods",
    "Medical services",
    "Pharmacy",
    "Wellbeing",
  ],
  "Hobby and leisure": [
    "Cabin",
    "Crafts",
    "Dating",
    "Events",
    "Exercise",
    "Gift card",
    "Loans for hobby and leisure",
    "Movie Theater",
    "Museum",
    "Online marketplace",
    "Pets",
    "Photography",
    "Postal services",
    "Recreational activities",
    "Toys",
    "Web services",
  ],
  "Home and garden": [
    "Appliances",
    "Furniture and interior",
    "Garden and flowers",
    "Home improvement",
    "Kitchenware",
    "Tools",
    "Tradesperson",
  ],
  "Income": [
    "Salary",
    "Dividends",
    "Other income",
    "Wages",
  ],
  "Insurance": [],
  "Kindergarten and after-school care": [],
  "Media and entertainment": [
    "Apps and gaming",
    "Bookseller",
    "Gambling",
    "Magazines",
    "Newspaper",
    "Streaming services",
    "TV",
  ],
  "Miscellaneous": [
    "Cash machine",
    "Credit card payment",
    "Digital currency",
    "Gift",
    "Interest",
    "Interest and fees",
    "Membership and charity",
    "Other expenses",
    "Payment",
    "Peer-to-peer payment",
    "Reimbursed expenses",
    "Safe deposit box",
    "Taxes",
    "Training and education",
    "Transfer",
  ],
  "Other loan and debt": [
    "Debt collection",
    "Other loans",
    "Student loan",
  ],
  "Savings": [],
  "Transportation and vehicles": [
    "Car dealership",
    "Car parts and maintenance",
    "Car rental",
    "Driver's education",
    "Fuel and charging",
    "Mechanic",
    "Parking",
    "Public transport",
    "Taxi",
    "Toll",
    "Vehicle fees",
  ],
  "Travel": [
    "Accommodation",
    "Other travel",
    "Phone tickets",
    "Travel agency",
  ],
  "Uncategorized": ["Unknown"],
};



export const CATEGORY_COLORS = {
  "Cafe and restaurant": "#FF6B6B",
  "Car insurance and car loan": "#4ECDC4",
  "Children": "#FFD93D",
  "Clothing and gear": "#6A0572",
  "Fixed living expenses": "#2C3E50",
  "Groceries": "#27AE60",
  "Health and wellbeing": "#2D2C8E",
  "Hobby and leisure": "#E67E22",
  "Home and garden": "#2980B9",
  "Income": "#2ECC71",
  "Insurance": "#95A5A6",
  "Kindergarten and after-school care": "#D35400",
  "Media and entertainment": "#3498DB",
  "Miscellaneous": "#7F8C8D",
  "Other loan and debt": "#E74C3C",
  "Savings": "#16A085",
  "Transportation and vehicles": "#9B59B6",
  "Travel": "#1ABC9C",
  "Uncategorized": "#BDC3C7",
};

export const SUB_CATEGORY_COLORS = {
  "Bars and nightlife": "#FF6B6B",
  "Cafe": "#FF6B6B",
  "Cafeteria": "#FF6B6B",
  "Candy": "#FF6B6B",
  "Convenience store": "#FF6B6B",
  "Fast food": "#FF6B6B",
  "Restaurant": "#FF6B6B",

  "Children's store": "#FFD93D",
  "Other child expenses": "#FFD93D",

  "Clothing": "#6A0572",
  "Jewelry and accessories": "#6A0572",
  "Shoes": "#6A0572",
  "Sporting goods": "#6A0572",

  "Alarm": "#2C3E50",
  "Electricity": "#2C3E50",
  "Home insurance": "#2C3E50",
  "Housing expenses": "#2C3E50",
  "Internet": "#2C3E50",
  "Mortgage": "#2C3E50",
  "Municipal fees": "#2C3E50",
  "Phone service": "#2C3E50",
  "Property management": "#2C3E50",
  "Rental and sales": "#2C3E50",

  "Grocery store": "#27AE60",
  "Other household items": "#27AE60",


  "Beauty": "#2D2C8E",
  "Dentist": "#2D2C8E",
  "Eye care": "#2D2C8E",
  "Health goods": "#2D2C8E",
  "Medical services": "#2D2C8E",
  "Pharmacy": "#2D2C8E",
  "Wellbeing": "#2D2C8E",

  "Cabin": "#E67E22",
  "Crafts": "#E67E22",
  "Dating": "#E67E22",
  "Events": "#E67E22",
  "Exercise": "#E67E22",
  "Gift card": "#E67E22",
  "Loans for hobby and leisure": "#E67E22",
  "Movie Theater": "#E67E22",
  "Museum": "#E67E22",
  "Online marketplace": "#E67E22",
  "Pets": "#E67E22",
  "Photography": "#E67E22",
  "Postal services": "#E67E22",
  "Recreational activities": "#E67E22",
  "Toys": "#E67E22",
  "Web services": "#E67E22",

  "Appliances": "#2980B9",
  "Furniture and interior": "#2980B9",
  "Garden and flowers": "#2980B9",
  "Home improvement": "#2980B9",
  "Kitchenware": "#2980B9",
  "Tools": "#2980B9",
  "Tradesperson": "#2980B9",

  "Salary": "#2ECC71",
  "Dividends": "#2ECC71",
  "Other income": "#2ECC71",
  "Wages": "#2ECC71",

  "Apps and gaming": "#3498DB",
  "Bookseller": "#3498DB",
  "Gambling": "#3498DB",
  "Magazines": "#3498DB",
  "Newspaper": "#3498DB",
  "Streaming services": "#3498DB",
  "TV": "#3498DB",

  "Cash machine": "#7F8C8D",
  "Credit card payment": "#7F8C8D",
  "Digital currency": "#7F8C8D",
  "Gift": "#7F8C8D",
  "Interest": "#7F8C8D",
  "Interest and fees": "#7F8C8D",
  "Membership and charity": "#7F8C8D",
  "Other expenses": "#7F8C8D",
  "Payment": "#7F8C8D",
  "Peer-to-peer payment": "#7F8C8D",
  "Reimbursed expenses": "#7F8C8D",
  "Safe deposit box": "#7F8C8D",
  "Taxes": "#7F8C8D",
  "Training and education": "#7F8C8D",
  "Transfer": "#7F8C8D",

  "Debt collection": "#E74C3C",
  "Other loans": "#E74C3C",
  "Student loan": "#E74C3C",

  "Car dealership": "#9B59B6",
  "Car parts and maintenance": "#9B59B6",
  "Car rental": "#9B59B6",
  "Driver's education": "#9B59B6",
  "Fuel and charging": "#9B59B6",
  "Mechanic": "#9B59B6",
  "Parking": "#9B59B6",
  "Public transport": "#9B59B6",
  "Taxi": "#9B59B6",
  "Toll": "#9B59B6",
  "Vehicle fees": "#9B59B6",

  "Accommodation": "#1ABC9C",
  "Other travel": "#1ABC9C",
  "Phone tickets": "#1ABC9C",
  "Travel agency": "#1ABC9C",

  "Unknown": "#BDC3C7"
};